%
% Title: proj3.m
% Summary: driver m-script for Project 3 for MATH 3315
% Author: Zack Fout
% Version: 1.1
% Last Modified: 04/06/2014
% Notes: Completed code for Part 1, need to add comments
%

%% *MATH 3315 Project 3 - Interpolation - By Zack Fout*
%% Part 1. Computing Interpolating Polynomials with Lagrange Polynomials
xNodes = [0, 2, 3, 5, 6];
fNodes = [1, 5, 0, -3, 2];
x = linspace(0, 6, 500);
y = lagrange(x, xNodes, fNodes);
figure('Units', 'pixels', ...
    'Position', [100 100 600 600]);
plot(x, y, ...
  'LineStyle', '-', ...
  'LineWidth', 2, ...
  'Color', 'r');

hold on;

plot(xNodes, fNodes, 'bo', ...
  'LineWidth', 3, ...
  'MarkerSize', 10, ...
  'MarkerEdgeColor', 'b', ...
  'MarkerFaceColor', 'y');

hTitle = title('The Lagrange Interpolating Polynomial');
hXLabel = xlabel('x');
hYLabel = ylabel('P(x)');
hLegend = legend({'P(x) = {\Sigma}{y_k}{L_k(x)}', 'Given Data'}, ...
    'Location', 'northeast');

set([hXLabel, hYLabel, hTitle, hLegend], ...
    'FontName', 'Courier 10 Pitch', ...
    'FontSize', 14, ...
    'FontWeight', 'bold');

set(gca, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'TickLength', [.02 .02], ...
    'XMinorTick', 'on', ...
    'YMinorTick', 'on');
